services:
  mysql:
    image: mysql:8
    container_name: car_rental_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rental
      MYSQL_USER: car_user
      MYSQL_PASSWORD: strong_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
